ecommerce/common/urls.py
from django.urls import path
from .import views

app_name='common'

urlpatterns=[
    path('',views.home,name='home'),
    path('clogin',views.customer_login,name='customer_login'),
    path('slogin',views.seller_login,name='seller_login'),
    path('creg',views.customer_reg,name='customer_reg'),
    path('sreg/',views.seller_reg,name='seller_reg'),


]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('customer/', include('customer.urls')),
    path('seller/', include('seller.urls')),
    path('ecomadmin/', include('ecom_admin.urls')),


] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

ecommerce/common/models.py
from django.db import models

# Create your models here.

class Customer(models.Model):
    customer_name = models.CharField(max_length=20)
    email = models.CharField(max_length=50)
    address = models.CharField(max_length=200)
    phone = models.BigIntegerField(default=0)
    gender = models.CharField(max_length=10)
    password = models.CharField(max_length=10,default='')
    status = models.CharField(max_length=10,default='active')

    class Meta:
        db_table = 'customer' 

class Seller(models.Model):
    seller_name =models.CharField(max_length=20)
    email = models.CharField(max_length = 50,default='')
    address = models.CharField(max_length = 200)
    phone = models.BigIntegerField()
    gender = models.CharField(max_length = 15)
    username = models.IntegerField(null=True)
    password = models.CharField(max_length=20,default='')
    company_name = models.CharField(max_length = 30)
    holder_name =  models.CharField(max_length = 20)
    ifsc = models.CharField(max_length = 50)
    branch = models.CharField(max_length = 50)
    account_number = models.BigIntegerField()
    image = models.ImageField(upload_to = 'seller/',default='static/image/dummy.jpg' )
    status = models.CharField(max_length = 20, default = 'pending')

    class Meta:
        db_table = 'seller'

    

ecommerce/common/views.py
from django.shortcuts import render,redirect
from .models import Customer,Seller

# Create your views here.

def home(request):
    return render(request,'common/home.html')

def seller_reg(request):

    msg =''

    if request.method == 'POST':
        sname = request.POST['seller_name']
        semail = request.POST['email']
        sphone = request.POST['phone']
        saddress = request.POST['address']
        sgender = request.POST['gender']
        sholder_name = request.POST['holder_name']
        scompany_name = request.POST['company_name']
        sifsc = request.POST['ifsc']
        sbranch = request.POST['branch']
        saccno = request.POST['acc_number']
        # simage = request.FILES['image']

        if 'image' in request.FILES:
            simage = request.FILES['image']

            seller=Seller(seller_name=sname, email=semail, phone=sphone, address=saddress, gender=sgender, holder_name=sholder_name, company_name=scompany_name,branch=sbranch, ifsc=sifsc, account_number=saccno, image=simage )
        else:
            seller=Seller(seller_name=sname, email=semail, phone=sphone, address=saddress, gender=sgender, holder_name=sholder_name, company_name=scompany_name,branch=sbranch, ifsc=sifsc, account_number=saccno )

        seller.save()

        msg = 'You have registered successfully'



    return render(request,'common/seller_reg.html',{'success_msg':msg})

def customer_reg(request):

    msg = ''
    msg2 = ''


    if request.method == 'POST':
        cname = request.POST['customer_name']
        cemail = request.POST['email']
        cphone = request.POST['phone']
        caddress = request.POST['address']
        cgender = request.POST['gender']
        cpassword = request.POST['password']

        email_exist = Customer.objects.filter(email = cemail).exists()

        if email_exist == False:

            customer = Customer(customer_name=cname, email=cemail, phone=cphone, address=caddress, gender=cgender, password=cpassword)
            customer.save()
            
            msg = 'you have registered successfully'


        else:
            msg2 = 'Email is already exist , please use another valid email'


    return render(request,'common/customer_reg.html',{'customer_msg':msg,'exist_msg':msg2})

def seller_login(request):
    msg=''

    if request.method == 'POST':
       
        
        user_name = request.POST['username']
        password = request.POST['password']

        try:
            seller = Seller.objects.get(username = user_name ,password = password)
            request.session['seller'] = seller.id  #seller in quotes is a key
            return redirect('seller:home')   #redirect into home page of seller app

        except Exception as e:
            print(e)
            msg= 'username or password is incorrect!!!'
            

    return render(request,'common/seller_login.html',{'message':msg})

def customer_login(request):

    msg = ''

    if request.method == 'POST':

        email = request.POST['email']
        password = request.POST['password']

        try:
            customer = Customer.objects.get(email = email ,password = password)
            request.session['customer'] = customer.id  
            return redirect('customer:home')   #redirect into home page of seller app

        except Exception as e:
            print(e)
            msg= 'email or password is incorrect!!!'

    return render(request,'common/customer_login.html',{'login_msg':msg})

ecommerce/common/templates/common/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
{% block header %}{% endblock %}
  </head>
<body>

  
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-md">
          <h1 class="navbar-brand  mx-auto fw-bold fs-5" href="#">ONLINE SHOPPING CART</h1>
        </div>
      </nav>

    {% block content%}
    
    {%endblock content%}


    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

ecommerce/common/templates/common/customer_login.html
{% extends 'common/base.html' %}
{% load static %}
{% block content%}

<section class="login mb-5" >
    <div class="container my-5 mx-5">
        <h1 class="text-center fw-bold">CUSTOMER LOGIN</h1>
    <h6 class="text-danger text-center bg-white">{{ login_msg }}</h6>

        <div class="row align-items-center shadow border-0">
            <div class="col-lg-5 col-12">
                <img src="{% static '/image/login.jpg' %}" alt="" class="img-fluid">

            </div>
            <div class="col-lg-7 col-12">
                <form method="POST">
                {% csrf_token %}

                  
                    <div class="mb-3">
                      <label for="exampleInputEmail1" class="form-label fw-bold">Email address</label>
                      <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
                    </div>
                    <div class="mb-3">
                      <label for="exampleInputPassword1" class="form-label fw-bold">Password</label>
                      <input type="password" class="form-control" id="exampleInputPassword1" name="password">
                    </div>
                   
                    <button type="submit" class="btn btn-dark">Login</button><br>
                  </form><br>
                  <p>Don't have an account?<a href="{% url 'common:customer_reg' %}" style="color: blue;" class="btn fw-bold">Create an account</a></p>

            </div>
        </div>
    </div>
</section>
{% endblock %}

ecommerce/common/templates/common/customer_reg.html
{% extends 'common/base.html' %}
{% load static %}
{% block content%}

<section class="signup mb-5" style="background-color: cadetblue;">
    <div class="row align-items-center">
    <h1 class="text-center" style=" font-weight: bold;">CUSTOMER REGISTRATION</h1>
    <!-- <a href="{% url 'common:customer_login' %}" style="margin-left: 1200px;"><button type="button" class="btn btn-warning">login</button></a> -->
  </div>

    <h6 class="text-success text-center bg-white">{{ customer_msg }}</h6>
    <h6 class="text-danger text-center bg-white">{{ exist_msg }}</h6>



    <div class="container my-5 mx-auto">
        <div class="row align-items-center shadow border-0  pt-5 pb-5 bg-white">
           
            <div class="col-lg-8 col-8 ">
              <form method="POST">
                {% csrf_token %}
                    <label class="control-label" for="date">Your Name</label>
                      <div class="mb-3">
                          <input type="text" class="form-control" placeholder="name" aria-label="First name" name="customer_name">
                        </div>
                                             
                    <div class="mb-3">
                      <label for="exampleInputEmail1" class="form-label">Email address</label>
                      <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
                    </div>
                    <div class="mb-3">
                        <label for="exampleFormControlTextarea1" class="form-label">Address</label>
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="address"></textarea>
                      </div>
                      <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Phone number</label>
                        <input type="number" class="form-control" name="phone">
                      </div>
                      <div class="mb-3">
                        <label class="control-label" for="date">Gender</label><br><br>
                        <input type="radio"  id="" name="gender">Male
                        <input type="radio" id="" name="gender">Female
                    </div>
                    <div class="mb-3">
                      <label for="exampleInputPassword1" class="form-label">Password</label>
                      <input type="password" class="form-control" id="exampleInputPassword1" name="password">
                    </div>
                    
                    
                    <button type="submit" class="btn btn-dark">Create</button><br>
                  </form>

            </div>
        </div>
    </div>
</section>
{% endblock content%}

ecommerce/common/templates/common/home.html
{% extends 'common/base.html' %}
{% load static %}
{% block header %}

{% endblock%} 
{{block.super}}


{% block content%}



<div class="cotainer-fluid">
    <div class="row">
        <div class="col-12">
            <img src="{% static 'image/home.png'%}" class="img-fluid border-rounded mt-5 " alt="..." width="100%">

                <a href="{% url 'common:customer_login' %}"><button type="button" class="btn btn-dark " style="position: relative; bottom: 400px;left: 50px;"> CUSTOMER</button></a>
                <a href="{% url 'common:seller_login' %}"><button type="button" class="btn btn-dark" style="position: relative; bottom: 400px;left: 1100px;"> SELLER</button></a>

        </div>
    </div>
</div>
</section>



    
{% endblock content %}

ecommerce/common/templates/common/seller_login.html
{% extends 'common/base.html' %}
{% load static %}
{% block content%}

<section class="login mb-5" >
    <div class="container my-5 mx-5">
        <h1 class="text-center fw-bold">SELLER LOGIN</h1>
        <div class="row align-items-center shadow border-0 ">
            <div class="col-lg-5 col-12">
                <img src="{% static '/image/login.jpg' %}" alt="" class="img-fluid">

            </div>
            <div class="col-lg-7 col-12">

                <form method="POST">

                  {% csrf_token %}

                    <div class="mb-3">
                      <label for="username" class="form-label fw-bold">Username</label>
                      <input type="name" class="form-control" id="username" name="username">
                    </div>
                    <div class="mb-3">
                      <label for="exampleInputPassword1" class="form-label fw-bold">Password</label>
                      <input type="password" class="form-control" id="exampleInputPassword1" name="password">
                    </div>
                 
                    <button type="submit" class="btn btn-dark">Login</button><br>
                    <span style="color: red;">{{ message }}</span>
                  </form><br>
                  <p>Don't have an account?<a href="{% url 'common:seller_reg' %}" style="color: blue;" class="btn fw-bold">Create an account</a></p>
            </div>
        </div>
    </div>
</section>
{% endblock %}

ecommerce/common/templates/common/seller_reg.html
{% extends 'common/base.html' %}
{% load static %}
{% block content%}

<!-- <section class="signup mb-5" style="background-color: cadetblue;"> -->
    <section  style="background-color: cadetblue;height: 100%;">
        <h4 class="text-center pt-4">SELLER REGISTRATION</h4>
        <h6 class="text-success text-center bg-white">{{ success_msg }}</h6>
        <div class="container py-5" style="height:100%">
            <div class="row d-flex justify-content-center align-items-center">
                <div class="col-md-8">
                    <div class="card" style="border-radius: 1rem;height:1100px;width:700px">
                        <div class="row g-0">
                            <div class="col-md-8 d-flex align-items-center">
                                <div class="card-body p-4 p-lg-5 text-black">
    
                                    <form method="POST" enctype="multipart/form-data">
                                            {% csrf_token %}
    
                                        <!-- to error: add class "has-danger" -->
                                        <div class="form-group">
                                            <label for="Inputname">Name</label>
                                            <input type="text" name="seller_name" class="form-control form-control-sm mt-3" id="Inputname">
                                        </div>
                                        <div class="form-group">
                                            <label for="Inputemail">Email</label>
                                            <input type="text" name="email" class="form-control form-control-sm mt-3"
                                                id="Inputemail">
                                        </div>
                                        <div class="form-group">
                                            <label for="Inputaddress">Address</label>
                                            <textarea class="form-control form-control-sm mt-3" name="address" id="Inputaddress"></textarea>
                                        </div>
                                        <div class="form-group">
                                            <label for="Inputphone">Phone</label>
                                            <input type="number" name="phone" class="form-control form-control-sm mt-3" id="Inputphone">
                                        <div class="form-group">
                                            <label for="Inputgender">Gender</label><br><br>
                                            <label>Male</label>&nbsp;&nbsp;
                                            <input type="radio" name="gender" id="male" value="male">&nbsp;&nbsp;&nbsp;&nbsp;
                                            <label>Female</label>&nbsp;&nbsp;&nbsp;&nbsp;
                                            <input type="radio" name="gender" id="female" value="female">
                                            <label>Transgender</label>&nbsp;&nbsp;&nbsp;&nbsp;
                                            <input type="radio" name="gender" id="trans" value="trans">
                                        </div>
                                        <div class="form-group mt-3">
                                            <label for="Inputcompany">Company Name</label>
                                            <input type="text" name="company_name" class="form-control form-control-sm mt-3"
                                                id="Inputcompanyname">
                                        </div>
                                        <div class="form-group mt-3">
                                            <label for="Inputcompany">Account holder Name</label>
                                            <input type="text"  name="holder_name" class="form-control form-control-sm mt-3"
                                                id="Inputaccname">
                                        </div>
    
                                        <div class="form-group mt-3">
                                            <label for="Inputifsc">IFSC Code</label>
                                            <input type="text"  name="ifsc" class="form-control form-control-sm mt-3"
                                                id="Inputcompanyname">
                                        </div>
    
                                        <div class="form-group mt-3">
                                            <label for="Inputbranch">Branch</label>
                                            <input type="text"  name ="branch" class="form-control form-control-sm mt-3"
                                                id="Inputcompanyname">
                                        </div>
    
                                        <div class="form-group mt-3">
                                            <label for="Inputaccno">Account Number</label>
                                            <input type="number" name="acc_number" class="form-control form-control-sm mt-3"
                                                id="Inputcompanyname">
                                        </div>
                                        <div class="form-group mt-3">
                                            <label for="Inputimage">Seller Image</label>
                                            <input type="file" id="file-ip-1"  name ="image" accept="image/*" onchange="showPreview(event)" class="form-control mt-3" />
                                        </div>
    
                                        
    
                                        
                                        <button type="submit" class="btn btn-primary btn-block mt-5 text-center">Submit</button>
    
                                       
                                    </form>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content%}