ecommerce/common/urls.py
from django.urls import path
from .import views

app_name='common'

urlpatterns=[
    path('',views.home,name='home'),
    path('clogin',views.customer_login,name='customer_login'),
    path('slogin',views.seller_login,name='seller_login'),
    path('creg',views.customer_reg,name='customer_reg'),
    path('sreg/',views.seller_reg,name='seller_reg'),


]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('customer/', include('customer.urls')),
    path('seller/', include('seller.urls')),
    path('ecomadmin/', include('ecom_admin.urls')),


] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

ecommerce/seller/urls.py
from django.urls import path
from .import views

app_name='seller'

urlpatterns=[
    path('',views.home,name='home'),
    path('add',views.add_product,name='add_product'),
    path('catalogue',views.catalogue,name='catalogue'),
    path('cpass',views.change_password,name='change_password'),
    path('orderhistory',views.order_history,name='order_history'),
    path('recentorders',views.recent_orders,name='recent_orders'),
    path('updatestock',views.update_stock,name='update_stock'),
    path('profile',views.profile,name='profile'),


    

]

ecommerce/seller/models.py
from django.db import models
from common.models import Seller

# Create your models here.

class Products(models.Model):
    product_name = models.CharField(max_length=20)
    seller = models.ForeignKey(Seller,on_delete=models.CASCADE)
    description = models.CharField(max_length=200)
    stock = models.IntegerField()
    image = models.ImageField(upload_to = 'products/')
    price = models.FloatField()
    code = models.CharField(max_length=10, default='')


    class Meta:
        db_table = 'product' 

ecommerce/seller/views.py
from django.shortcuts import render
from common.models import Seller 
from seller.models import Products

# Create your views here.

def home(request):
    # seller = Seller.objects.get(id = request.session ['seller'])
    seller = Seller.objects.filter(id= request.session['seller']).values('seller_name','image')
    seller_name = seller[0]['seller_name']
    seller_pic = seller[0]['image']

    # return render(request,'seller/home.html',{'seller_data':seller})
    return render(request,'seller/home.html',{'name':seller_name,'image':seller_pic })


def add_product(request):

    msg=''
    msg2= ''

    if request.method == 'POST':

        product_name = request.POST['product_name']
        description = request.POST['description']
        price = request.POST['product_price']
        stock = request.POST['product_stock']
        code = request.POST['product_code']
        product_image = request.FILES['product_image']
        

        product_exist = Products.objects.filter(code = code ,seller = request.session['seller']).exists()  #it returns false or true
        if not product_exist:            #(if product_exist == false)

            product = Products(product_name = product_name , description = description , price = price , stock = stock , image = product_image , code = code , seller_id = request.session['seller'])
            product.save()
            msg ='product added successfully'

        else:

            msg2 = 'product is already added'

#product(model_name : view name)
        

    return render(request,'seller/add_product.html',{'product_msg':msg , 'exist_msg': msg2})

def catalogue(request):

    products = Products.objects.filter(seller = request.session['seller'])



    return render(request,'seller/catalogue.html',{'products':products})

def change_password(request):

    error_msg = ''
    success_msg = ''

    if request.method == 'POST':

        old_pass = request.POST['old_password']
        new_pass = request.POST['new_password']
        confirm_pass = request.POST['confirm_password']

        if new_pass == confirm_pass :

            if len(new_pass) >= 8 :

                seller = Seller.objects.get(id = request.session['seller'])

                if seller.password == old_pass :

                    seller.password = new_pass
                    seller.save()
                    success_msg = 'password changed successfully'

                else:
                    error_msg = 'old password is incorrect'

            else:

                error_msg = 'passwords should be 8 characters'


        else:
            error_msg = 'passwords doesn\'t match'

        

    return render(request,'seller/change_password.html',{'success_msg':success_msg,'error_msg':error_msg})

def order_history(request):
    return render(request,'seller/order_history.html')

def recent_orders(request):
    return render(request,'seller/recent_orders.html')

def update_stock(request):
    return render(request,'seller/update_stock.html')

def profile(request):
    return render(request,'seller/profile.html')

ecommerce/seller/templates/seller/add_product.html
{% extends 'seller/base.html' %} {% load static %} {% block header %} {%endblock%} {{block.super}} {% block content%}

<div style="margin-left: 20%">
  <div class="w3-container w3-teal bg-dark">
    <h2 class="text-white">ADD PRODUCT</h2>
  </div>

  <h6 class="text-success text-center bg-white">{{ product_msg }}</h6>

  <h6 class="text-danger text-center bg-white">{{ exist_msg }}</h6>

  <section style="height: 100%">
    <div class="container py-2" style="height: 100%">
      <div class="row d-flex justify-content-center align-items-center">
        <div class="col-md-8">
          <div
            class="card"
            style="border-radius: 1rem; height: 650px; width: 700px"
          >
            <div class="row g-0">
              <div class="col-md-8 d-flex align-items-center">
                <div class="card-body p-4 p-lg-5 text-black">
                  <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

                    <!-- to error: add class "has-danger" -->
                    <div class="form-group">
                      <label for="Inputname">Product Name</label>
                      <input
                        type="text"
                        name="product_name"
                        class="form-control form-control-sm mt-3"
                        id="Inputname"
                      />
                    </div>
                    <div class="form-group">
                      <label for="Inputdescription">Description</label>
                      <textarea
                        name="description"
                        class="form-control form-control-sm mt-3"
                        id="Inputdescription"
                      ></textarea>
                    </div>
                    <!-- <div class="form-group">
                                            <label for="Inputcategory">Category</label>
                                            <input type="text" class="form-control form-control-sm mt-3" name="category" id="Inputcategory"></textarea>
                                        </div> -->
                    <div class="form-group">
                      <label for="Inputstock">Product stock</label>
                      <input
                        type="text"
                        class="form-control form-control-sm mt-3"
                        name="product_stock"
                        id="Inputstock"
                      />
                    </div>
                    <div class="form-group">
                      <label for="Inputprice">Product code</label>
                      <input
                        type="text"
                        class="form-control form-control-sm mt-3"
                        name="product_code"
                        id="Inputprice"
                      />
                    </div>
                    <div class="form-group">
                      <label for="Inputprice">Product Price</label>
                      <input
                        type="text"
                        class="form-control form-control-sm mt-3"
                        name="product_price"
                        id="Inputprice"
                      />
                    </div>
                    <div class="form-group mt-3">
                      <label for="Inputimage">Product Image</label>
                      <input
                        type="file"
                        id="file-ip-1"
                        name="product_image"
                        onchange="showPreview(event)"
                        class="form-control mt-3"
                      />
                    </div>
                    <button
                      type="submit"
                      class="btn btn-primary btn-block mt-5 text-center"
                    >
                      Submit
                    </button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

{% endblock%}

ecommerce/seller/templates/seller/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
{% block header %}{% endblock %}
  </head>
<body>

  
    <div class="w3-sidebar w3-light-grey w3-bar-block pb-5" style="width:20%">
        
        <h3 class="w3-bar-item">Menu</h3>
        <a href="{% url 'seller:home' %}" class="w3-bar-item w3-button fw-bold mb-3"> Home</a>
        <a href="{% url 'seller:catalogue' %}" class="w3-bar-item w3-button fw-bold mb-3"> Product Catalogue</a>
        <a href="{% url 'seller:add_product' %}" class="w3-bar-item w3-button fw-bold mb-3"> Add Product</a>
        <a href="{% url 'seller:change_password' %}" class="w3-bar-item w3-button fw-bold mb-3"> Change Password</a>
        <a href="{% url 'seller:profile' %}" class="w3-bar-item w3-button fw-bold mb-3"> Profile</a>
        <a href="{% url 'seller:recent_orders' %}" class="w3-bar-item w3-button fw-bold mb-3"> Recent Orders</a>
        <a href="{% url 'seller:update_stock' %}" class="w3-bar-item w3-button fw-bold mb-3"> Update Stock</a>
        <a href="{% url 'seller:order_history' %}" class="w3-bar-item w3-button fw-bold mb-3"> Order History</a>
      
    </div>

    {% block content%}
    
    {%endblock content%}


    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>

ecommerce/seller/templates/seller/catalogue.html
{% extends 'seller/base.html' %}
{% load static %}
{% block header %}

{% endblock%} 
{{block.super}}


{% block content%}

<div style="margin-left:20%">
  <div class="w3-container w3-teal bg-dark">
    <h2 class="text-white">PRODUCT CATALOGUE</h2>
  </div>



    <div class="row pt-4 align-items-center gy-4  ">
{% for product in products %}
      <div class="col-lg-3 col-md-6 col-sm-12 mx-sm-auto">
        <div class="card " style="width: 16rem;">
          <img class="card-img-top" src="{{ product.image.url }}" alt="Card image cap" height="300px">
            <div class="card-body">
              <h5 class="card-title">{{ product.product_name }}</h5>
              <p class="card-text text-dark fw-bold">#{{ product.code}}</p>

              <p class="card-text text-warning">Rs .{{ product.price }}</p>
              <p class="card-text text-info00">Description : {{ product.description }}</p>
              <p class="card-text text-danger">Stock : {{ product.stock }}</p>

              <p class="card-text text-dark">Seller is :{{ product.seller.seller_name }}</p>
            </div>  
        </div>
      </div>

      {% endfor %}
    </div>
  </div>


       





{% endblock%} 

ecommerce/seller/templates/seller/change_password.html
{% extends 'seller/base.html' %}
{% load static %}
{% block header %}

{% endblock%} 
{{block.super}}


{% block content%}

<div style="margin-left:20%">
    <div class="w3-container w3-teal bg-dark">
        <h2 class="text-white">CHANGE PASSWORD</h2>
      </div>

    <section class="vh-100">

      <h6 class="text-success text-center bg-white">{{ success_msg }}</h6>
      <h6 class="text-danger text-center bg-white">{{ error_msg }}</h6>


        
        <div class="container py-5" style="height:400px">
          <div class="row d-flex justify-content-center align-items-center">
             <div class="col col-xl-10">
              <div class="card" style="border-radius: 1rem;height:450px;width:500px">
                 <div class="row g-0">
                   <div class="col-md-6 col-lg-5 d-none d-md-block">
                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/img1.webp"
                      alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem; height:450px;" />
                  </div> 
                  <div class="col-md-6 col-lg-7 d-flex align-items-center">
                    <div class="card-body p-4 p-lg-5 text-black">
      
                      <form method="POST">

                        {% csrf_token %}
      
      
                        <!-- to error: add class "has-danger" -->
                        <div class="form-group">
                          <label for="Inputpswd1">Old Password</label>
                          <input type="password" name="old_password" class="form-control form-control-sm mt-3" id="Inputoldpaswd"
                            aria-describedby="emailHelp">
                        </div>
                        <div class="form-group">
                          <label for="InputPswd2">New Password</label>
                          <input type="password"  name="new_password" class="form-control form-control-sm mt-3" id="Inputnewpassword">
                        </div>
                        <div class="form-group">
                            <label for="Inputpswd3">Confirm Password</label>
                            <input type="password"  name="confirm_password" class="form-control form-control-sm mt-3" id="Inputconfirmpassword">
                          </div>
                        <button type="submit" class="btn btn-primary btn-block mt-5">Submit</button>
      
                        
                      </form>
                    </div>
                  </div>
                </div>
               </div> 
             </div>
           </div> 
        </div>
      </section>





</div>






{% endblock%} 

ecommerce/seller/templates/seller/home.html
{% extends 'seller/base.html' %}
{% load static %}
{% block header %}

{% endblock%} 
{{block.super}}


{% block content%}


<!-- Page Content -->
<div style="margin-left:20%">

<div class="w3-container w3-teal bg-dark">
  <h1 class="text-white">WELCOME {{ name |  upper }}</h1>
</div>

<img src=" /media/{{ image }}" alt="image" style="width:500px ;height: 300px;margin-top: 50px;margin-left: 200px;" >



</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
crossorigin="anonymous"></script>

{% endblock%} 

      
</body>
</html>

ecommerce/seller/templates/seller/order_history.html
{% extends 'seller/base.html' %}
{% load static %}
{% block header %}

{% endblock%} 
{{block.super}}


{% block content%}

<div style="margin-left:20%">
    <div class="w3-container w3-teal bg-dark">
        <h2 class="text-white">ORDER HISTORY</h2>
    </div>







</div>






{% endblock%} 

ecommerce/seller/templates/seller/profile.html
{% extends 'seller/base.html' %}
{% load static %}
{% block header %}

{% endblock%} 
{{block.super}}


{% block content%}

<div style="margin-left:20%">

    <div class="w3-container w3-teal bg-dark">
        <h1 class="text-white">PROFILE</h1>
    </div>









</div>






{% endblock%} 

ecommerce/seller/templates/seller/recent_orders.html
{% extends 'seller/base.html' %}
{% load static %}
{% block header %}

{% endblock%} 
{{block.super}}


{% block content%}

<div style="margin-left:20%">
    <div class="w3-container w3-teal bg-dark">
        <h2 class="text-white">RECENT ORDERS</h2>
    </div>







</div>






{% endblock%} 

ecommerce/seller/templates/seller/update_stock.html
{% extends 'seller/base.html' %} 

{% load static %}
{% block content%}

<div style="margin-left: 20%">
  <div class="w3-container w3-teal bg-dark">
    <h2 class="text-white">UPDATE STOCK</h2>
  </div>

  <div class="row ms-4">
    <div class="col-md-6 col-12">
      <div style="border-radius: 1rem; height: 800px; width: 1000px ;margin-top: 100px;">
        <form>
          <table class="table table-striped table-hover">
            <tr>
              <td>
                <label for="selectproduct"><b> Product</b></label>
                <div class="dropdown">
                  <button
                    class="btn btn-secondary dropdown-toggle"
                    type="button"
                    id="dropdownMenuButton1"
                    data-bs-toggle="dropdown"
                    aria-expanded="false"
                  >
                    select product
                  </button>
                  <ul
                    class="dropdown-menu"
                    aria-labelledby="dropdownMenuButton1"
                  >
                    <li><a class="dropdown-item" href="#">1</a></li>
                    <li><a class="dropdown-item" href="#">2</a></li>
                    <li><a class="dropdown-item" href="#">3</a></li>
                  </ul>
                </div>
              </td>
              <td>
                <div class="form-group">
                  <label for="curentstock"><b>Current Stock</b> </label>
                  <input
                    type="number"
                    name="current_stock"
                    size="10"
                    class="form-control form-control-sm mt-3"
                    id="Inputcurrentstock"
                  />
                </div>
              </td>
              <td>
                <div class="form-group">
                  <label for="curentstock"><b>New Stock</b> </label>
                  <input
                    type="number"
                    name="new_stock"
                    size="10"
                    class="form-control form-control-sm mt-3"
                    id="Inputcurrentstock"
                  />
                </div>
              </td>
            </tr>
          </table>

          <div class="d-grid gap-2 col-6 mx-auto">
            <button class="btn btn-dark" name="submit">Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock%}