ecommerce/common/urls.py
from django.urls import path
from .import views

app_name='common'

urlpatterns=[
    path('',views.home,name='home'),
    path('clogin',views.customer_login,name='customer_login'),
    path('slogin',views.seller_login,name='seller_login'),
    path('creg',views.customer_reg,name='customer_reg'),
    path('sreg/',views.seller_reg,name='seller_reg'),


]

ecommerce/customer/urls.py
from django.urls import path
from .import views

app_name='customer'

urlpatterns=[
    path('',views.home,name='home'),
    path('cart',views.cart,name='cart'),
    path('changepassword',views.changepassword,name='changepassword'),
    path('orders',views.orders,name='orders'),
    path('products',views.products,name='products'),
    path('profile',views.profile,name='profile'),
    path('product/<int:pid>',views.product_details,name='product_details'),


    



]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('customer/', include('customer.urls')),
    path('seller/', include('seller.urls')),
    path('ecomadmin/', include('ecom_admin.urls')),


] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

ecommerce/customer/models.py
from django.db import models
from common.models import Customer
from seller.models import Products

# Create your models here.

class Cart(models.Model) :
    customer = models.ForeignKey(Customer,on_delete=models.CASCADE)
    product = models.ForeignKey(Products,on_delete=models.CASCADE)


    class Meta:
        db_table = 'cart'
    


       

ecommerce/customer/views.py
from django.shortcuts import render,redirect
from seller.models import Products
from common.models import Customer
from customer.models import Cart

# Create your views here.


def home(request):
    return render(request,'customer/home.html')
def cart(request):
    cart = Cart.objects.filter(customer = request.session['customer'])

    return render(request,'customer/cart.html',{'cart':cart})
def orders(request):
    return render(request,'customer/orders.html')
def products(request):

    products = Products.objects.all()
    return render(request,'customer/products.html',{'products': products})
    
def changepassword(request):


    error_msg = ''
    success_msg = ''

    if request.method == 'POST':

        old_pass = request.POST['old_password']
        new_pass = request.POST['new_password']
        confirm_pass = request.POST['confirm_password']

        if new_pass == confirm_pass :

            if len(new_pass) >= 8 :

                customer = Customer.objects.get(id = request.session['customer'])

                if customer.password == old_pass :

                    # customer.password = new_pass
                    # customer.save()

                    Customer.objects.filter(id = request.session['customer']).update( password = new_pass )
                    success_msg = 'password changed successfully'

                else:
                    error_msg = 'old password is incorrect'

            else:

                error_msg = 'passwords should be 8 characters'


        else:
            error_msg = 'passwords doesn\'t match'

    return render(request,'customer/changepassword.html',{'success_msg':success_msg,'error_msg':error_msg})
def profile(request):
    return render(request,'customer/profile.html')

def product_details(request,pid):
    error_msg = ''

    product = Products.objects.get( id = pid )

    if request.method == 'POST':
        customer = request.session['customer']   #getting customer id from session

        record_exist = Cart.objects.filter( product = pid ,customer = customer ).exists()

        if record_exist == False:  # if not record_exist

            cart = Cart(customer_id = customer ,product_id = pid)
            cart.save()
            return redirect('customer:cart')


        else:

            error_msg = 'item already in cart'


        

    return render(request,'customer/product_details.html',{'product_details':product , 'message':error_msg})

ecommerce/customer/templates/customer/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/customer.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
<script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>

  </head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <H2 class="text-white">MENS FASHION</H2>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mx-auto mb-2 mb-lg-0 pe-3" id="wanted">
              <li class="nav-item">
                <a class="nav-link active me-5" aria-current="page" href="{% url 'customer:home' %}">Home</a>
              </li>
             
              <li class="nav-item">
                <a class="nav-link active me-3" aria-current="page" href="{% url 'customer:products' %}">Products</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link active me-3" aria-current="page" href="{% url 'customer:orders' %}">Orders</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active me-3" aria-current="page" href="{% url 'customer:changepassword' %}">Change Password</a>
              </li>
             
              <div style="margin-left: 250px;"></div>
              <li class="nav-item">
                <a class="nav-link active me-3" aria-current="page" href="{% url 'customer:cart' %}"><i class="bi bi-cart-fill"></i></a>
              </li>
              <li class="nav-item me-3">
                <a class="nav-link active " aria-current="page" href=""><i class="bi bi-box-arrow-right"></i></a>
              </li>
              <li class="nav-item">
                <a class="nav-link active me-3" aria-current="page" href="{% url 'customer:profile' %}"><i class="bi bi-person-fill"></i></a>
              </li>
            </div>
              
             
            </ul>
            
          </div>
        </div>
      </nav>

  
    {% block content%}
    
    {%endblock content%}

    <!-- Footer -->
<footer class="page-footer font-small blue pt-4  bg-dark text-white">

  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-6 mt-md-0 mt-3">

        <!-- Content -->
        <h5 class="text-uppercase">MENS FASHION</h5>
        <p>Here you can use rows and columns to organize your footer content.</p>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none pb-3">

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->

      

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Contact Us</a>
          </li>
          <li>
            <a href="#!">About Us</a>
          </li>
          <li>
            <a href="#!"><i class="bi bi-linkedin"></i>Linkdn</a>
          </li>
        
        </ul>

      </div>
    </div>

  </div>

  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="/"> mensfashion.com</a>
  </div>

</footer>


    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>

ecommerce/customer/templates/customer/cart.html
{% extends 'customer/base.html' %}
{% load static %}
{% block header %}

{% endblock%} 
{{block.super}}


{% block content%}
<table class="table">
    <thead>
      <tr>
        <th scope="col">sl.no.</th>
        <th scope="col">Product image</th>
        <th scope="col">ProductName</th>
        <th scope="col">Price</th>
        <th scope="col">Quantity</th>
        <th scope="col">TotalPrice</th>
      </tr>
    </thead>
    <tbody>
   {% for product in cart %}

   <tr>

      <td>{{ forloop.counter }}</td>
      <td><img src="{{ product.product.image.url }}"  height="100px" alt=""></td>
      <td>{{ product.product.product_name }}</td>
      <td class="price">{{ product.product.price }}</td>
      <td><input type="number" min="1" value="1" max="{{ product.product.stock }}" class="quantity"   item-price ="{{ product.product.price }}" item-id ="{{ product.product.id }}"   >{{ product.product.quantity }}</td>
      <td  > <span id="span{{product.product.id}}"></span></td>

</tr>

  {% endfor %}


    



     
    </tbody>
  </table>

  <script>

   $('input').change( function(){

    price = $(this).attr('item-price')
    qty = $(this).val()
    id =$(this).attr('item-id')

    total_price = parseInt(price) * parseInt(qty)

    selected_span_id = 'span' + id

    // console.log(total_price)
    // console.log(selected_span_id)
    document.getElementById(selected_span_id).innerHTML = total_price

   })


  </script>






{% endblock%} 

ecommerce/customer/templates/customer/changepassword.html
{% extends 'customer/base.html' %}
{% load static %}
{% block header %}

{% endblock%} 
{{block.super}}


{% block content%}
<section class="vh-100">
    <h4 class=" pt-2" style="margin-left:550px">CHANGE PASSWORD</h4>
    <h6 class="text-success text-center bg-white">{{ success_msg }}</h6>
    <h6 class="text-danger text-center bg-white">{{ error_msg }}</h6>
    <div class="container py-5" style="height:400px ;margin-left: 300px;">
      <div class="row d-flex justify-content-center align-items-center">
         <div class="col col-xl-10">
          <div class="card" style="border-radius: 1rem;height:450px;width:500px">
             <div class="row g-0">
               <div class="col-md-6 col-lg-5 d-none d-md-block">
                <img src="{% static 'image/customer.jpg'%}"
                  alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem; height:450px;" />
              </div> 
              <div class="col-md-6 col-lg-7 d-flex align-items-center">
                <div class="card-body p-4 p-lg-5 text-black">
  
                  <form method="POST">

                    {% csrf_token %}
  
  
                    <!-- to error: add class "has-danger" -->
                    <div class="form-group">
                      <label for="Inputpswd1">Old Password</label>
                      <input type="password" name="old_password" class="form-control form-control-sm mt-3" id="Inputoldpaswd"
                        aria-describedby="emailHelp">
                    </div>
                    <div class="form-group">
                      <label for="InputPswd2">New Password</label>
                      <input type="password"  name="new_password" class="form-control form-control-sm mt-3" id="Inputnewpassword">
                    </div>
                    <div class="form-group">
                        <label for="Inputpswd3">Confirm Password</label>
                        <input type="password"  name="confirm_password" class="form-control form-control-sm mt-3" id="Inputconfirmpassword">
                      </div>
                    <button type="submit" class="btn btn-primary btn-block mt-5">Submit</button>
  
                    
                  </form>
                </div>
              </div>
            </div>
           </div> 
         </div>
       </div> 
    </div>
  </section>












{% endblock%} 

ecommerce/customer/templates/customer/home.html
{% extends 'customer/base.html' %}
{% load static %}
{% block header %}

{% endblock%} 
{{block.super}}


{% block content%}


<div id="carouselExampleControls" class=" carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'image/home1.jpg' %}" class="d-block w-100" alt="..." style="border-radius: 10%;width: 100%;">
      </div>
      <div class="carousel-item">
        <img src="{% static 'image/home2.jpg' %}" class="d-block w-100" alt="..." style="border-radius: 10%;width: 100%;">
      </div>
      <div class="carousel-item">
        <img src="{% static 'image/home3.jpg' %}" class="d-block w-100" alt="..." style="border-radius: 10%;width: 100%;">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>






{% endblock%} 

ecommerce/customer/templates/customer/orders.html
{% extends 'customer/base.html' %}
{% load static %}
{% block header %}

{% endblock%} 
{{block.super}}


{% block content%}








{% endblock%} 

ecommerce/customer/templates/customer/product_details.html
{% extends 'customer/base.html' %}
{% load static %}
{% block header %}

{% endblock%} 
{{block.super}}


{% block content%}


  <div class="container p-5">
    <div class="row">
        <div class="col-lg-6 col-sm-12 mx-auto">
            <img class="card-img-top border-2" src="{{ product_details.image.url }}" alt="Card image cap" height="400px">
            
        </div>
        <div class="col-lg-6 col-sm-12 mx-auto my-auto ">
            <form method="POST">
                {% csrf_token %}

            <h3 class="card-title">{{ product_details.product_name }}</h3>
            <p class="card-text text-warning fw-bold">Rs . {{ product_details.price }}</p>
  
            <p class="card-text text-dark">Description : {{ product_details.description }}</p>
            <p class="card-text text-danger">Stock :{{ product_details.stock }}</p>
            <p class="card-text text-dark">Seller is :{{ product_details.seller.seller_name }}</p>
            
             <button    class="btn btn-dark mt-3">Add to Cart</button>
             <h6 class="text-danger text-center bg-white">{{ message }}</h6>

            </form>

        </div>

    </div>
  </div>










{% endblock%} 

ecommerce/customer/templates/customer/products.html
{% extends 'customer/base.html' %}
{% load static %}
{% block header %}

{% endblock%} 
{{block.super}}


{% block content%}

<div class="row pt-4 align-items-center gy-4  ">
  
  {% for product in products %}
  
      <div class="col-lg-3 col-md-6 col-sm-12 mx-sm-auto">
        <a href="{% url 'customer:product_details' product.id %}" class=" text-decoration-none">
          <div class="card " style="width: 16rem;">
           <img class="card-img-top" src="{{ product.image.url }}" alt="Card image cap">
            <div class="card-body">
             <h5 class="card-title text-dark text-decoration-none">{{ product.product_name }}</h5>
             <p class="card-text text-warning">Rs . {{ product.price }}</p>
  
             <a href="#" class="btn btn-dark mt-3">Add to Cart</a>
            </div>
          </div>
        </a>
      </div>
  
  {% endfor %}
    
</div>


    <!-- second row -->

    







{% endblock%} 

ecommerce/customer/templates/customer/profile.html
{% extends 'customer/base.html' %}
{% load static %}
{% block header %}

{% endblock%} 
{{block.super}}


{% block content%}



<main class="container">
 
  <!-- Left Column / Headphones Image -->
  <div class="left-column">
    <img data-image="black" src="images/black.png" alt="">
    <img data-image="blue" src="images/blue.png" alt="">
    <img data-image="red" class="active" src="images/red.png" alt="">
  </div>
 
 
  <!-- Right Column -->
  <div class="right-column">
 
    <!-- Product Description -->
    <div class="product-description">
      <span>Headphones</span>
      <h1>Beats EP</h1>
      <p>The preferred choice of a vast range of acclaimed DJs. Punchy, bass-focused sound and high isolation. Sturdy headband and on-ear cushions suitable for live performance</p>
    </div>
 
    <!-- Product Configuration -->
    <div class="product-configuration">
 
      <!-- Product Color -->
      <div class="product-color">
        <span>Color</span>
 
        <div class="color-choose">
          <div>
            <input data-image="red" type="radio" id="red" name="color" value="red" checked>
            <label for="red"><span></span></label>
          </div>
          <div>
            <input data-image="blue" type="radio" id="blue" name="color" value="blue">
            <label for="blue"><span></span></label>
          </div>
          <div>
            <input data-image="black" type="radio" id="black" name="color" value="black">
            <label for="black"><span></span></label>
          </div>
        </div>
 
      </div>
 
      <!-- Cable Configuration -->
      <div class="cable-config">
        <span>Cable configuration</span>
 
        <div class="cable-choose">
          <button>Straight</button>
          <button>Coiled</button>
          <button>Long-coiled</button>
        </div>
 
        <a href="#">How to configurate your headphones</a>
      </div>
    </div>
 
    <!-- Product Pricing -->
    <div class="product-price">
      <span>148$</span>
      <a href="#" class="cart-btn">Add to cart</a>
    </div>
  </div>
</main>






{% endblock%} 