ecommerce/common/urls.py
from django.urls import path
from .import views

app_name='common'

urlpatterns=[
    path('',views.home,name='home'),
    path('clogin',views.customer_login,name='customer_login'),
    path('slogin',views.seller_login,name='seller_login'),
    path('creg',views.customer_reg,name='customer_reg'),
    path('sreg/',views.seller_reg,name='seller_reg'),


]

ecommerce/ecom_admin/urls.py
from django.urls import path
from .import views

app_name='ecom_admin'

urlpatterns=[
    path('',views.home,name='home'),
    path('apseller',views.approve_seller,name='approve_seller'),
    path('viewseller',views.view_seller,name='view_seller'),
    path('viewcustomer',views.view_customer,name='view_customer'),

    
    
    


]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('customer/', include('customer.urls')),
    path('seller/', include('seller.urls')),
    path('ecomadmin/', include('ecom_admin.urls')),


] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

ecommerce/ecom_admin/models.py
from django.db import models

# Create your models here.

ecommerce/ecom_admin/views.py
from django.shortcuts import render
from common.models import Seller
from django.core.mail import send_mail
from random import randint
from django.conf import settings 


# Create your views here.



def home(request):
    return render(request,'ecom_admin/home.html')

def approve_seller(request):

    sellers = Seller.objects.filter(status ='pending')

    if request.method == 'POST':
        seller_id= request.POST['seller_id']
        seller = Seller.objects.get(id = seller_id)

        if 'approve' in request.POST:
            #login when approve button clicked
            user_name = randint(1111,9999)
            password = 'sel-' + str(user_name) + str(seller.phone)[:5]
            
            seller.status = 'approved' #sql update query
            seller.username = user_name
            seller.password = password
            seller.save()

            #setting type of username,password and message

           
            mail_subject = 'Account Approval'
            message_body = 'Hi your account has been approved by admin , you can now login with username ' +str(user_name)+ 'and temporary password '+ password

            
        if 'reject' in request.POST:
            
            seller.status = 'rejected' 
            seller.save()

            
            mail_subject = 'Account Rejected'
            message_body = 'sorry your account has been rejected by admin '


        send_mail(
                subject=mail_subject,
                message=message_body,
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[seller.email]
            )

    return render(request,'ecom_admin/approve_seller.html',{ 'sellers_list' : sellers  })

def view_seller(request):

    seller =Seller.objects.filter(status='approved')

    return render(request,'ecom_admin/view_seller.html',{'seller_list' : seller})

def view_customer(request):
    return render(request,'ecom_admin/view_customer.html')

ecommerce/ecom_admin/templates/ecom_admin/approve_seller.html
{% extends 'ecom_admin/base.html' %}
{% load static %}
{% block header %}
{{block.super}}


{% endblock%} 


{% block content%}







    <h2 class="text-center bg-success">Approve Seller</h2>
    <table class="table table-striped table-hover">
            
        <thead>
            <tr>

                <th scope ="col">SNo</th>
                <th scope ="col">Name</th>
                <th scope ="col">Email</th>
                <th scope ="col">Acc.No</th>
                <th scope ="col">IFSC</th>
                <th scope ="col">Branch</th>
                <th scope ="col">Company Name</th>

                <th scope ="col">Phone</th>
                <th scope ="col">Seller pic</th>
                <th scope ="col">Actions</th>

            </tr>

            {% for seller in sellers_list %}
            <form method="POST">
                {% csrf_token %}
            <tr>
                 <td>{{ forloop.counter }}</td>      <!-- for counting serial number -->
                <td>{{ seller.seller_name }}</td>
                <td>{{ seller.email }}</td>
                <td>{{ seller.account_number }}</td>
                <td>{{ seller.ifsc }}</td>
                <td>{{ seller.branch }}</td>
                <td>{{ seller.company_name }}</td>
                <td>{{ seller.phone }}</td>
                <td><img src="{{ seller.image.url }}" alt="" width="80px"></td>
                <td><button type="'submit" name="approve" class="btn btn-success">Approve</button></td>
                <td><button type="'submit" name="reject" class="btn btn-danger">Reject</button></td>
                <td><input type="hidden" value="{{seller.id}}" name="seller_id"></td>

             </tr>
            </form>

            {% endfor %}

        </thead>
    </table>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
{% endblock%} 

ecommerce/ecom_admin/templates/ecom_admin/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/admin.css' %}">

  </head>
<body>

  <h6>fhjrgjer</h6>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <h1 class="text-white">ADMIN PANEL</h1>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mx-auto mb-2 mb-lg-0 pe-3">
              <li class="nav-item">
                <a class="nav-link active me-4" aria-current="page" href="{% url 'ecom_admin:approve_seller' %}">Approve Seller</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active  me-4" aria-current="page" href="{% url 'ecom_admin:view_seller' %}">View Seller</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'ecom_admin:view_customer' %}">View Customer</a>
              </li>
              
          </div>
        </div>
      </nav>

    {% block content%}
    
    {%endblock content%}


    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

ecommerce/ecom_admin/templates/ecom_admin/home.html
{% extends 'ecom_admin/base.html' %}
{% load static %}
{% block header %}

{% endblock%} 
{{block.super}}


{% block content%}
<div class="">
    <img src="{% static 'image/admin.jpg' %}" alt="" class="img" width="100%">
</div>






{% endblock%} 

ecommerce/ecom_admin/templates/ecom_admin/view_customer.html
{% extends 'ecom_admin/base.html' %}
{% load static %}
{% block header %}

{% endblock%} 
{{block.super}}


{% block content%}

    <h2 class="text-center bg-success">View Customer</h2>






{% endblock%} 

ecommerce/ecom_admin/templates/ecom_admin/view_seller.html
{% extends 'ecom_admin/base.html' %}
{% load static %}
{% block header %}

{% endblock%} 
{% block content%}

<h2 class="text-center bg-success">View Seller</h2>

<table class="table table-striped table-hover">
            
    <thead>
        <tr>

            <th scope ="col">SNo</th>
            <th scope ="col">Name</th>
            <th scope ="col">Email</th>
            <th scope ="col">Acc.No</th>
            <th scope ="col">IFSC</th>
            <th scope ="col">Branch</th>
            <th scope ="col">Company Name</th>
            <th scope ="col">Phone</th>
            <th scope ="col">Seller photo</th>

        </tr>
       
        
        {% for seller in seller_list %}
        <form method="POST">
            {% csrf_token %}
        <tr>
             <td>{{ forloop.counter }}</td>      <!-- for counting serial number -->
            <td>{{ seller.seller_name }}</td>
            <td>{{ seller.email }}</td>
            <td>{{ seller.account_number }}</td>
            <td>{{ seller.ifsc }}</td>
            <td>{{ seller.branch }}</td>
            <td>{{ seller.company_name }}</td>
            <td>{{ seller.phone }}</td>
            {% if seller.image == 'static/image/dummy.jpg' %}

            <td><img src="{% static 'image/dummy.jpg' %}" alt="" width="80px"></td>
            {% else %}
            <td><img src="{{ seller.image.url }}" alt="" width="80px"></td>
            {% endif %}
           

         </tr>
        </form>

        {% endfor %}

    </thead>

</table>
    





{% endblock%} 